plugins {
    alias(libs.plugins.android.application)

}

android {
    namespace 'com.example.myCourse'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.myCourse"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        buildConfigField "String", "X_INTERNAL_SECRET", "\"120aaa50332843eb2fa099ca042150dde0879651a881e6efd5130099785551c9fb3fc64029b58dbeb99ff923047bbb43a32f3f1c15e4463d0636ebeb373ae594\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildToolsVersion '34.0.0'


}

dependencies {

    //def room_version = "2.6.1"

    implementation "androidx.room:room-runtime:2.6.1"

    // If this project uses any Kotlin source, use Kotlin Symbol Processing (KSP)
    // See KSP Quickstart to add KSP to your build
    //ksp "androidx.room:room-compiler:2.6.1"

    // If this project only uses Java source, use the Java annotationProcessor
    // No additional plugins are necessary
    annotationProcessor "androidx.room:room-compiler:2.6.1"

    // optional - RxJava2 support for Room
    implementation "androidx.room:room-rxjava2:2.6.1"

    // optional - RxJava3 support for Room
    implementation "androidx.room:room-rxjava3:2.6.1"

    // optional - Guava support for Room, including Optional and ListenableFuture
    implementation "androidx.room:room-guava:2.6.1"

    // optional - Test helpers
    testImplementation "androidx.room:room-testing:2.6.1"

    // optional - Paging 3 Integration
    implementation "androidx.room:room-paging:2.6.1"
    // Google used to prep Data for serialization
    implementation 'com.google.code.gson:gson:2.10.1'

    //Retrofit Serialization
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'



    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation 'org.postgresql:postgresql:42.7.4'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

}